// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: popeye/proto/message.proto

package popeye.proto;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AttributeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string name = 1;
    boolean hasName();
    String getName();
    
    // required string value = 2;
    boolean hasValue();
    String getValue();
  }
  public static final class Attribute extends
      com.google.protobuf.GeneratedMessage
      implements AttributeOrBuilder {
    // Use Attribute.newBuilder() to construct.
    private Attribute(Builder builder) {
      super(builder);
    }
    private Attribute(boolean noInit) {}
    
    private static final Attribute defaultInstance;
    public static Attribute getDefaultInstance() {
      return defaultInstance;
    }
    
    public Attribute getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return popeye.proto.Message.internal_static_popeye_proto_Attribute_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return popeye.proto.Message.internal_static_popeye_proto_Attribute_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string value = 2;
    public static final int VALUE_FIELD_NUMBER = 2;
    private java.lang.Object value_;
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          value_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      name_ = "";
      value_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getValueBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getValueBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static popeye.proto.Message.Attribute parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static popeye.proto.Message.Attribute parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static popeye.proto.Message.Attribute parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static popeye.proto.Message.Attribute parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static popeye.proto.Message.Attribute parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static popeye.proto.Message.Attribute parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static popeye.proto.Message.Attribute parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static popeye.proto.Message.Attribute parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static popeye.proto.Message.Attribute parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static popeye.proto.Message.Attribute parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(popeye.proto.Message.Attribute prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements popeye.proto.Message.AttributeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return popeye.proto.Message.internal_static_popeye_proto_Attribute_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return popeye.proto.Message.internal_static_popeye_proto_Attribute_fieldAccessorTable;
      }
      
      // Construct using popeye.proto.Message.Attribute.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return popeye.proto.Message.Attribute.getDescriptor();
      }
      
      public popeye.proto.Message.Attribute getDefaultInstanceForType() {
        return popeye.proto.Message.Attribute.getDefaultInstance();
      }
      
      public popeye.proto.Message.Attribute build() {
        popeye.proto.Message.Attribute result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private popeye.proto.Message.Attribute buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        popeye.proto.Message.Attribute result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public popeye.proto.Message.Attribute buildPartial() {
        popeye.proto.Message.Attribute result = new popeye.proto.Message.Attribute(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof popeye.proto.Message.Attribute) {
          return mergeFrom((popeye.proto.Message.Attribute)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(popeye.proto.Message.Attribute other) {
        if (other == popeye.proto.Message.Attribute.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              value_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string name = 1;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
      }
      
      // required string value = 2;
      private java.lang.Object value_ = "";
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setValue(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      void setValue(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:popeye.proto.Attribute)
    }
    
    static {
      defaultInstance = new Attribute(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:popeye.proto.Attribute)
  }
  
  public interface PointOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string metric = 1;
    boolean hasMetric();
    String getMetric();
    
    // required int64 timestamp = 2;
    boolean hasTimestamp();
    long getTimestamp();
    
    // repeated .popeye.proto.Attribute attributes = 3;
    java.util.List<popeye.proto.Message.Attribute> 
        getAttributesList();
    popeye.proto.Message.Attribute getAttributes(int index);
    int getAttributesCount();
    java.util.List<? extends popeye.proto.Message.AttributeOrBuilder> 
        getAttributesOrBuilderList();
    popeye.proto.Message.AttributeOrBuilder getAttributesOrBuilder(
        int index);
    
    // optional int64 int_value = 4;
    boolean hasIntValue();
    long getIntValue();
    
    // optional float float_value = 5;
    boolean hasFloatValue();
    float getFloatValue();
  }
  public static final class Point extends
      com.google.protobuf.GeneratedMessage
      implements PointOrBuilder {
    // Use Point.newBuilder() to construct.
    private Point(Builder builder) {
      super(builder);
    }
    private Point(boolean noInit) {}
    
    private static final Point defaultInstance;
    public static Point getDefaultInstance() {
      return defaultInstance;
    }
    
    public Point getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return popeye.proto.Message.internal_static_popeye_proto_Point_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return popeye.proto.Message.internal_static_popeye_proto_Point_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string metric = 1;
    public static final int METRIC_FIELD_NUMBER = 1;
    private java.lang.Object metric_;
    public boolean hasMetric() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getMetric() {
      java.lang.Object ref = metric_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          metric_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMetricBytes() {
      java.lang.Object ref = metric_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        metric_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int64 timestamp = 2;
    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_;
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getTimestamp() {
      return timestamp_;
    }
    
    // repeated .popeye.proto.Attribute attributes = 3;
    public static final int ATTRIBUTES_FIELD_NUMBER = 3;
    private java.util.List<popeye.proto.Message.Attribute> attributes_;
    public java.util.List<popeye.proto.Message.Attribute> getAttributesList() {
      return attributes_;
    }
    public java.util.List<? extends popeye.proto.Message.AttributeOrBuilder> 
        getAttributesOrBuilderList() {
      return attributes_;
    }
    public int getAttributesCount() {
      return attributes_.size();
    }
    public popeye.proto.Message.Attribute getAttributes(int index) {
      return attributes_.get(index);
    }
    public popeye.proto.Message.AttributeOrBuilder getAttributesOrBuilder(
        int index) {
      return attributes_.get(index);
    }
    
    // optional int64 int_value = 4;
    public static final int INT_VALUE_FIELD_NUMBER = 4;
    private long intValue_;
    public boolean hasIntValue() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public long getIntValue() {
      return intValue_;
    }
    
    // optional float float_value = 5;
    public static final int FLOAT_VALUE_FIELD_NUMBER = 5;
    private float floatValue_;
    public boolean hasFloatValue() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public float getFloatValue() {
      return floatValue_;
    }
    
    private void initFields() {
      metric_ = "";
      timestamp_ = 0L;
      attributes_ = java.util.Collections.emptyList();
      intValue_ = 0L;
      floatValue_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasMetric()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getAttributesCount(); i++) {
        if (!getAttributes(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getMetricBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, timestamp_);
      }
      for (int i = 0; i < attributes_.size(); i++) {
        output.writeMessage(3, attributes_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(4, intValue_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFloat(5, floatValue_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getMetricBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, timestamp_);
      }
      for (int i = 0; i < attributes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, attributes_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, intValue_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, floatValue_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static popeye.proto.Message.Point parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static popeye.proto.Message.Point parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static popeye.proto.Message.Point parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static popeye.proto.Message.Point parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static popeye.proto.Message.Point parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static popeye.proto.Message.Point parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static popeye.proto.Message.Point parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static popeye.proto.Message.Point parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static popeye.proto.Message.Point parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static popeye.proto.Message.Point parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(popeye.proto.Message.Point prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements popeye.proto.Message.PointOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return popeye.proto.Message.internal_static_popeye_proto_Point_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return popeye.proto.Message.internal_static_popeye_proto_Point_fieldAccessorTable;
      }
      
      // Construct using popeye.proto.Message.Point.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAttributesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        metric_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (attributesBuilder_ == null) {
          attributes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          attributesBuilder_.clear();
        }
        intValue_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        floatValue_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return popeye.proto.Message.Point.getDescriptor();
      }
      
      public popeye.proto.Message.Point getDefaultInstanceForType() {
        return popeye.proto.Message.Point.getDefaultInstance();
      }
      
      public popeye.proto.Message.Point build() {
        popeye.proto.Message.Point result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private popeye.proto.Message.Point buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        popeye.proto.Message.Point result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public popeye.proto.Message.Point buildPartial() {
        popeye.proto.Message.Point result = new popeye.proto.Message.Point(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.metric_ = metric_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.timestamp_ = timestamp_;
        if (attributesBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            attributes_ = java.util.Collections.unmodifiableList(attributes_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.attributes_ = attributes_;
        } else {
          result.attributes_ = attributesBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.intValue_ = intValue_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.floatValue_ = floatValue_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof popeye.proto.Message.Point) {
          return mergeFrom((popeye.proto.Message.Point)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(popeye.proto.Message.Point other) {
        if (other == popeye.proto.Message.Point.getDefaultInstance()) return this;
        if (other.hasMetric()) {
          setMetric(other.getMetric());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (attributesBuilder_ == null) {
          if (!other.attributes_.isEmpty()) {
            if (attributes_.isEmpty()) {
              attributes_ = other.attributes_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureAttributesIsMutable();
              attributes_.addAll(other.attributes_);
            }
            onChanged();
          }
        } else {
          if (!other.attributes_.isEmpty()) {
            if (attributesBuilder_.isEmpty()) {
              attributesBuilder_.dispose();
              attributesBuilder_ = null;
              attributes_ = other.attributes_;
              bitField0_ = (bitField0_ & ~0x00000004);
              attributesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAttributesFieldBuilder() : null;
            } else {
              attributesBuilder_.addAllMessages(other.attributes_);
            }
          }
        }
        if (other.hasIntValue()) {
          setIntValue(other.getIntValue());
        }
        if (other.hasFloatValue()) {
          setFloatValue(other.getFloatValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasMetric()) {
          
          return false;
        }
        if (!hasTimestamp()) {
          
          return false;
        }
        for (int i = 0; i < getAttributesCount(); i++) {
          if (!getAttributes(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              metric_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              timestamp_ = input.readInt64();
              break;
            }
            case 26: {
              popeye.proto.Message.Attribute.Builder subBuilder = popeye.proto.Message.Attribute.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addAttributes(subBuilder.buildPartial());
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              intValue_ = input.readInt64();
              break;
            }
            case 45: {
              bitField0_ |= 0x00000010;
              floatValue_ = input.readFloat();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string metric = 1;
      private java.lang.Object metric_ = "";
      public boolean hasMetric() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getMetric() {
        java.lang.Object ref = metric_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          metric_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMetric(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        metric_ = value;
        onChanged();
        return this;
      }
      public Builder clearMetric() {
        bitField0_ = (bitField0_ & ~0x00000001);
        metric_ = getDefaultInstance().getMetric();
        onChanged();
        return this;
      }
      void setMetric(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        metric_ = value;
        onChanged();
      }
      
      // required int64 timestamp = 2;
      private long timestamp_ ;
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getTimestamp() {
        return timestamp_;
      }
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000002;
        timestamp_ = value;
        onChanged();
        return this;
      }
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      
      // repeated .popeye.proto.Attribute attributes = 3;
      private java.util.List<popeye.proto.Message.Attribute> attributes_ =
        java.util.Collections.emptyList();
      private void ensureAttributesIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          attributes_ = new java.util.ArrayList<popeye.proto.Message.Attribute>(attributes_);
          bitField0_ |= 0x00000004;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          popeye.proto.Message.Attribute, popeye.proto.Message.Attribute.Builder, popeye.proto.Message.AttributeOrBuilder> attributesBuilder_;
      
      public java.util.List<popeye.proto.Message.Attribute> getAttributesList() {
        if (attributesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(attributes_);
        } else {
          return attributesBuilder_.getMessageList();
        }
      }
      public int getAttributesCount() {
        if (attributesBuilder_ == null) {
          return attributes_.size();
        } else {
          return attributesBuilder_.getCount();
        }
      }
      public popeye.proto.Message.Attribute getAttributes(int index) {
        if (attributesBuilder_ == null) {
          return attributes_.get(index);
        } else {
          return attributesBuilder_.getMessage(index);
        }
      }
      public Builder setAttributes(
          int index, popeye.proto.Message.Attribute value) {
        if (attributesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributesIsMutable();
          attributes_.set(index, value);
          onChanged();
        } else {
          attributesBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setAttributes(
          int index, popeye.proto.Message.Attribute.Builder builderForValue) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          attributes_.set(index, builderForValue.build());
          onChanged();
        } else {
          attributesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAttributes(popeye.proto.Message.Attribute value) {
        if (attributesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributesIsMutable();
          attributes_.add(value);
          onChanged();
        } else {
          attributesBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addAttributes(
          int index, popeye.proto.Message.Attribute value) {
        if (attributesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributesIsMutable();
          attributes_.add(index, value);
          onChanged();
        } else {
          attributesBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addAttributes(
          popeye.proto.Message.Attribute.Builder builderForValue) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          attributes_.add(builderForValue.build());
          onChanged();
        } else {
          attributesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addAttributes(
          int index, popeye.proto.Message.Attribute.Builder builderForValue) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          attributes_.add(index, builderForValue.build());
          onChanged();
        } else {
          attributesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllAttributes(
          java.lang.Iterable<? extends popeye.proto.Message.Attribute> values) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          super.addAll(values, attributes_);
          onChanged();
        } else {
          attributesBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearAttributes() {
        if (attributesBuilder_ == null) {
          attributes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          attributesBuilder_.clear();
        }
        return this;
      }
      public Builder removeAttributes(int index) {
        if (attributesBuilder_ == null) {
          ensureAttributesIsMutable();
          attributes_.remove(index);
          onChanged();
        } else {
          attributesBuilder_.remove(index);
        }
        return this;
      }
      public popeye.proto.Message.Attribute.Builder getAttributesBuilder(
          int index) {
        return getAttributesFieldBuilder().getBuilder(index);
      }
      public popeye.proto.Message.AttributeOrBuilder getAttributesOrBuilder(
          int index) {
        if (attributesBuilder_ == null) {
          return attributes_.get(index);  } else {
          return attributesBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends popeye.proto.Message.AttributeOrBuilder> 
           getAttributesOrBuilderList() {
        if (attributesBuilder_ != null) {
          return attributesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(attributes_);
        }
      }
      public popeye.proto.Message.Attribute.Builder addAttributesBuilder() {
        return getAttributesFieldBuilder().addBuilder(
            popeye.proto.Message.Attribute.getDefaultInstance());
      }
      public popeye.proto.Message.Attribute.Builder addAttributesBuilder(
          int index) {
        return getAttributesFieldBuilder().addBuilder(
            index, popeye.proto.Message.Attribute.getDefaultInstance());
      }
      public java.util.List<popeye.proto.Message.Attribute.Builder> 
           getAttributesBuilderList() {
        return getAttributesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          popeye.proto.Message.Attribute, popeye.proto.Message.Attribute.Builder, popeye.proto.Message.AttributeOrBuilder> 
          getAttributesFieldBuilder() {
        if (attributesBuilder_ == null) {
          attributesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              popeye.proto.Message.Attribute, popeye.proto.Message.Attribute.Builder, popeye.proto.Message.AttributeOrBuilder>(
                  attributes_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          attributes_ = null;
        }
        return attributesBuilder_;
      }
      
      // optional int64 int_value = 4;
      private long intValue_ ;
      public boolean hasIntValue() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public long getIntValue() {
        return intValue_;
      }
      public Builder setIntValue(long value) {
        bitField0_ |= 0x00000008;
        intValue_ = value;
        onChanged();
        return this;
      }
      public Builder clearIntValue() {
        bitField0_ = (bitField0_ & ~0x00000008);
        intValue_ = 0L;
        onChanged();
        return this;
      }
      
      // optional float float_value = 5;
      private float floatValue_ ;
      public boolean hasFloatValue() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public float getFloatValue() {
        return floatValue_;
      }
      public Builder setFloatValue(float value) {
        bitField0_ |= 0x00000010;
        floatValue_ = value;
        onChanged();
        return this;
      }
      public Builder clearFloatValue() {
        bitField0_ = (bitField0_ & ~0x00000010);
        floatValue_ = 0F;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:popeye.proto.Point)
    }
    
    static {
      defaultInstance = new Point(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:popeye.proto.Point)
  }
  
  public interface BatchOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .popeye.proto.Point point = 1;
    java.util.List<popeye.proto.Message.Point> 
        getPointList();
    popeye.proto.Message.Point getPoint(int index);
    int getPointCount();
    java.util.List<? extends popeye.proto.Message.PointOrBuilder> 
        getPointOrBuilderList();
    popeye.proto.Message.PointOrBuilder getPointOrBuilder(
        int index);
    
    // optional int64 correlation = 2;
    boolean hasCorrelation();
    long getCorrelation();
  }
  public static final class Batch extends
      com.google.protobuf.GeneratedMessage
      implements BatchOrBuilder {
    // Use Batch.newBuilder() to construct.
    private Batch(Builder builder) {
      super(builder);
    }
    private Batch(boolean noInit) {}
    
    private static final Batch defaultInstance;
    public static Batch getDefaultInstance() {
      return defaultInstance;
    }
    
    public Batch getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return popeye.proto.Message.internal_static_popeye_proto_Batch_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return popeye.proto.Message.internal_static_popeye_proto_Batch_fieldAccessorTable;
    }
    
    private int bitField0_;
    // repeated .popeye.proto.Point point = 1;
    public static final int POINT_FIELD_NUMBER = 1;
    private java.util.List<popeye.proto.Message.Point> point_;
    public java.util.List<popeye.proto.Message.Point> getPointList() {
      return point_;
    }
    public java.util.List<? extends popeye.proto.Message.PointOrBuilder> 
        getPointOrBuilderList() {
      return point_;
    }
    public int getPointCount() {
      return point_.size();
    }
    public popeye.proto.Message.Point getPoint(int index) {
      return point_.get(index);
    }
    public popeye.proto.Message.PointOrBuilder getPointOrBuilder(
        int index) {
      return point_.get(index);
    }
    
    // optional int64 correlation = 2;
    public static final int CORRELATION_FIELD_NUMBER = 2;
    private long correlation_;
    public boolean hasCorrelation() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getCorrelation() {
      return correlation_;
    }
    
    private void initFields() {
      point_ = java.util.Collections.emptyList();
      correlation_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getPointCount(); i++) {
        if (!getPoint(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < point_.size(); i++) {
        output.writeMessage(1, point_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(2, correlation_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < point_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, point_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, correlation_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static popeye.proto.Message.Batch parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static popeye.proto.Message.Batch parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static popeye.proto.Message.Batch parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static popeye.proto.Message.Batch parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static popeye.proto.Message.Batch parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static popeye.proto.Message.Batch parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static popeye.proto.Message.Batch parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static popeye.proto.Message.Batch parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static popeye.proto.Message.Batch parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static popeye.proto.Message.Batch parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(popeye.proto.Message.Batch prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements popeye.proto.Message.BatchOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return popeye.proto.Message.internal_static_popeye_proto_Batch_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return popeye.proto.Message.internal_static_popeye_proto_Batch_fieldAccessorTable;
      }
      
      // Construct using popeye.proto.Message.Batch.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPointFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (pointBuilder_ == null) {
          point_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          pointBuilder_.clear();
        }
        correlation_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return popeye.proto.Message.Batch.getDescriptor();
      }
      
      public popeye.proto.Message.Batch getDefaultInstanceForType() {
        return popeye.proto.Message.Batch.getDefaultInstance();
      }
      
      public popeye.proto.Message.Batch build() {
        popeye.proto.Message.Batch result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private popeye.proto.Message.Batch buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        popeye.proto.Message.Batch result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public popeye.proto.Message.Batch buildPartial() {
        popeye.proto.Message.Batch result = new popeye.proto.Message.Batch(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (pointBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            point_ = java.util.Collections.unmodifiableList(point_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.point_ = point_;
        } else {
          result.point_ = pointBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.correlation_ = correlation_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof popeye.proto.Message.Batch) {
          return mergeFrom((popeye.proto.Message.Batch)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(popeye.proto.Message.Batch other) {
        if (other == popeye.proto.Message.Batch.getDefaultInstance()) return this;
        if (pointBuilder_ == null) {
          if (!other.point_.isEmpty()) {
            if (point_.isEmpty()) {
              point_ = other.point_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePointIsMutable();
              point_.addAll(other.point_);
            }
            onChanged();
          }
        } else {
          if (!other.point_.isEmpty()) {
            if (pointBuilder_.isEmpty()) {
              pointBuilder_.dispose();
              pointBuilder_ = null;
              point_ = other.point_;
              bitField0_ = (bitField0_ & ~0x00000001);
              pointBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPointFieldBuilder() : null;
            } else {
              pointBuilder_.addAllMessages(other.point_);
            }
          }
        }
        if (other.hasCorrelation()) {
          setCorrelation(other.getCorrelation());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getPointCount(); i++) {
          if (!getPoint(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              popeye.proto.Message.Point.Builder subBuilder = popeye.proto.Message.Point.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addPoint(subBuilder.buildPartial());
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              correlation_ = input.readInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .popeye.proto.Point point = 1;
      private java.util.List<popeye.proto.Message.Point> point_ =
        java.util.Collections.emptyList();
      private void ensurePointIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          point_ = new java.util.ArrayList<popeye.proto.Message.Point>(point_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          popeye.proto.Message.Point, popeye.proto.Message.Point.Builder, popeye.proto.Message.PointOrBuilder> pointBuilder_;
      
      public java.util.List<popeye.proto.Message.Point> getPointList() {
        if (pointBuilder_ == null) {
          return java.util.Collections.unmodifiableList(point_);
        } else {
          return pointBuilder_.getMessageList();
        }
      }
      public int getPointCount() {
        if (pointBuilder_ == null) {
          return point_.size();
        } else {
          return pointBuilder_.getCount();
        }
      }
      public popeye.proto.Message.Point getPoint(int index) {
        if (pointBuilder_ == null) {
          return point_.get(index);
        } else {
          return pointBuilder_.getMessage(index);
        }
      }
      public Builder setPoint(
          int index, popeye.proto.Message.Point value) {
        if (pointBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePointIsMutable();
          point_.set(index, value);
          onChanged();
        } else {
          pointBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setPoint(
          int index, popeye.proto.Message.Point.Builder builderForValue) {
        if (pointBuilder_ == null) {
          ensurePointIsMutable();
          point_.set(index, builderForValue.build());
          onChanged();
        } else {
          pointBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addPoint(popeye.proto.Message.Point value) {
        if (pointBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePointIsMutable();
          point_.add(value);
          onChanged();
        } else {
          pointBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addPoint(
          int index, popeye.proto.Message.Point value) {
        if (pointBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePointIsMutable();
          point_.add(index, value);
          onChanged();
        } else {
          pointBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addPoint(
          popeye.proto.Message.Point.Builder builderForValue) {
        if (pointBuilder_ == null) {
          ensurePointIsMutable();
          point_.add(builderForValue.build());
          onChanged();
        } else {
          pointBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addPoint(
          int index, popeye.proto.Message.Point.Builder builderForValue) {
        if (pointBuilder_ == null) {
          ensurePointIsMutable();
          point_.add(index, builderForValue.build());
          onChanged();
        } else {
          pointBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllPoint(
          java.lang.Iterable<? extends popeye.proto.Message.Point> values) {
        if (pointBuilder_ == null) {
          ensurePointIsMutable();
          super.addAll(values, point_);
          onChanged();
        } else {
          pointBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearPoint() {
        if (pointBuilder_ == null) {
          point_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          pointBuilder_.clear();
        }
        return this;
      }
      public Builder removePoint(int index) {
        if (pointBuilder_ == null) {
          ensurePointIsMutable();
          point_.remove(index);
          onChanged();
        } else {
          pointBuilder_.remove(index);
        }
        return this;
      }
      public popeye.proto.Message.Point.Builder getPointBuilder(
          int index) {
        return getPointFieldBuilder().getBuilder(index);
      }
      public popeye.proto.Message.PointOrBuilder getPointOrBuilder(
          int index) {
        if (pointBuilder_ == null) {
          return point_.get(index);  } else {
          return pointBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends popeye.proto.Message.PointOrBuilder> 
           getPointOrBuilderList() {
        if (pointBuilder_ != null) {
          return pointBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(point_);
        }
      }
      public popeye.proto.Message.Point.Builder addPointBuilder() {
        return getPointFieldBuilder().addBuilder(
            popeye.proto.Message.Point.getDefaultInstance());
      }
      public popeye.proto.Message.Point.Builder addPointBuilder(
          int index) {
        return getPointFieldBuilder().addBuilder(
            index, popeye.proto.Message.Point.getDefaultInstance());
      }
      public java.util.List<popeye.proto.Message.Point.Builder> 
           getPointBuilderList() {
        return getPointFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          popeye.proto.Message.Point, popeye.proto.Message.Point.Builder, popeye.proto.Message.PointOrBuilder> 
          getPointFieldBuilder() {
        if (pointBuilder_ == null) {
          pointBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              popeye.proto.Message.Point, popeye.proto.Message.Point.Builder, popeye.proto.Message.PointOrBuilder>(
                  point_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          point_ = null;
        }
        return pointBuilder_;
      }
      
      // optional int64 correlation = 2;
      private long correlation_ ;
      public boolean hasCorrelation() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getCorrelation() {
        return correlation_;
      }
      public Builder setCorrelation(long value) {
        bitField0_ |= 0x00000002;
        correlation_ = value;
        onChanged();
        return this;
      }
      public Builder clearCorrelation() {
        bitField0_ = (bitField0_ & ~0x00000002);
        correlation_ = 0L;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:popeye.proto.Batch)
    }
    
    static {
      defaultInstance = new Batch(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:popeye.proto.Batch)
  }
  
  public interface BatchReplyOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int64 correlation = 1;
    boolean hasCorrelation();
    long getCorrelation();
    
    // required int64 batchId = 2;
    boolean hasBatchId();
    long getBatchId();
    
    // required .popeye.proto.BatchReply.Status status = 3;
    boolean hasStatus();
    popeye.proto.Message.BatchReply.Status getStatus();
  }
  public static final class BatchReply extends
      com.google.protobuf.GeneratedMessage
      implements BatchReplyOrBuilder {
    // Use BatchReply.newBuilder() to construct.
    private BatchReply(Builder builder) {
      super(builder);
    }
    private BatchReply(boolean noInit) {}
    
    private static final BatchReply defaultInstance;
    public static BatchReply getDefaultInstance() {
      return defaultInstance;
    }
    
    public BatchReply getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return popeye.proto.Message.internal_static_popeye_proto_BatchReply_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return popeye.proto.Message.internal_static_popeye_proto_BatchReply_fieldAccessorTable;
    }
    
    public enum Status
        implements com.google.protobuf.ProtocolMessageEnum {
      OK(0, 1),
      FAIL(1, 2),
      ;
      
      public static final int OK_VALUE = 1;
      public static final int FAIL_VALUE = 2;
      
      
      public final int getNumber() { return value; }
      
      public static Status valueOf(int value) {
        switch (value) {
          case 1: return OK;
          case 2: return FAIL;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Status>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Status>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Status>() {
              public Status findValueByNumber(int number) {
                return Status.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return popeye.proto.Message.BatchReply.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Status[] VALUES = {
        OK, FAIL, 
      };
      
      public static Status valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Status(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:popeye.proto.BatchReply.Status)
    }
    
    private int bitField0_;
    // required int64 correlation = 1;
    public static final int CORRELATION_FIELD_NUMBER = 1;
    private long correlation_;
    public boolean hasCorrelation() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getCorrelation() {
      return correlation_;
    }
    
    // required int64 batchId = 2;
    public static final int BATCHID_FIELD_NUMBER = 2;
    private long batchId_;
    public boolean hasBatchId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getBatchId() {
      return batchId_;
    }
    
    // required .popeye.proto.BatchReply.Status status = 3;
    public static final int STATUS_FIELD_NUMBER = 3;
    private popeye.proto.Message.BatchReply.Status status_;
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public popeye.proto.Message.BatchReply.Status getStatus() {
      return status_;
    }
    
    private void initFields() {
      correlation_ = 0L;
      batchId_ = 0L;
      status_ = popeye.proto.Message.BatchReply.Status.OK;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasCorrelation()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBatchId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, correlation_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, batchId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, status_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, correlation_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, batchId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, status_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static popeye.proto.Message.BatchReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static popeye.proto.Message.BatchReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static popeye.proto.Message.BatchReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static popeye.proto.Message.BatchReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static popeye.proto.Message.BatchReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static popeye.proto.Message.BatchReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static popeye.proto.Message.BatchReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static popeye.proto.Message.BatchReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static popeye.proto.Message.BatchReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static popeye.proto.Message.BatchReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(popeye.proto.Message.BatchReply prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements popeye.proto.Message.BatchReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return popeye.proto.Message.internal_static_popeye_proto_BatchReply_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return popeye.proto.Message.internal_static_popeye_proto_BatchReply_fieldAccessorTable;
      }
      
      // Construct using popeye.proto.Message.BatchReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        correlation_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        batchId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = popeye.proto.Message.BatchReply.Status.OK;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return popeye.proto.Message.BatchReply.getDescriptor();
      }
      
      public popeye.proto.Message.BatchReply getDefaultInstanceForType() {
        return popeye.proto.Message.BatchReply.getDefaultInstance();
      }
      
      public popeye.proto.Message.BatchReply build() {
        popeye.proto.Message.BatchReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private popeye.proto.Message.BatchReply buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        popeye.proto.Message.BatchReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public popeye.proto.Message.BatchReply buildPartial() {
        popeye.proto.Message.BatchReply result = new popeye.proto.Message.BatchReply(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.correlation_ = correlation_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.batchId_ = batchId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.status_ = status_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof popeye.proto.Message.BatchReply) {
          return mergeFrom((popeye.proto.Message.BatchReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(popeye.proto.Message.BatchReply other) {
        if (other == popeye.proto.Message.BatchReply.getDefaultInstance()) return this;
        if (other.hasCorrelation()) {
          setCorrelation(other.getCorrelation());
        }
        if (other.hasBatchId()) {
          setBatchId(other.getBatchId());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasCorrelation()) {
          
          return false;
        }
        if (!hasBatchId()) {
          
          return false;
        }
        if (!hasStatus()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              correlation_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              batchId_ = input.readInt64();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              popeye.proto.Message.BatchReply.Status value = popeye.proto.Message.BatchReply.Status.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                status_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int64 correlation = 1;
      private long correlation_ ;
      public boolean hasCorrelation() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getCorrelation() {
        return correlation_;
      }
      public Builder setCorrelation(long value) {
        bitField0_ |= 0x00000001;
        correlation_ = value;
        onChanged();
        return this;
      }
      public Builder clearCorrelation() {
        bitField0_ = (bitField0_ & ~0x00000001);
        correlation_ = 0L;
        onChanged();
        return this;
      }
      
      // required int64 batchId = 2;
      private long batchId_ ;
      public boolean hasBatchId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getBatchId() {
        return batchId_;
      }
      public Builder setBatchId(long value) {
        bitField0_ |= 0x00000002;
        batchId_ = value;
        onChanged();
        return this;
      }
      public Builder clearBatchId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        batchId_ = 0L;
        onChanged();
        return this;
      }
      
      // required .popeye.proto.BatchReply.Status status = 3;
      private popeye.proto.Message.BatchReply.Status status_ = popeye.proto.Message.BatchReply.Status.OK;
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public popeye.proto.Message.BatchReply.Status getStatus() {
        return status_;
      }
      public Builder setStatus(popeye.proto.Message.BatchReply.Status value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        status_ = value;
        onChanged();
        return this;
      }
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000004);
        status_ = popeye.proto.Message.BatchReply.Status.OK;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:popeye.proto.BatchReply)
    }
    
    static {
      defaultInstance = new BatchReply(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:popeye.proto.BatchReply)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_popeye_proto_Attribute_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_popeye_proto_Attribute_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_popeye_proto_Point_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_popeye_proto_Point_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_popeye_proto_Batch_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_popeye_proto_Batch_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_popeye_proto_BatchReply_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_popeye_proto_BatchReply_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032popeye/proto/message.proto\022\014popeye.pro" +
      "to\"(\n\tAttribute\022\014\n\004name\030\001 \002(\t\022\r\n\005value\030\002" +
      " \002(\t\"\177\n\005Point\022\016\n\006metric\030\001 \002(\t\022\021\n\ttimesta" +
      "mp\030\002 \002(\003\022+\n\nattributes\030\003 \003(\0132\027.popeye.pr" +
      "oto.Attribute\022\021\n\tint_value\030\004 \001(\003\022\023\n\013floa" +
      "t_value\030\005 \001(\002\"@\n\005Batch\022\"\n\005point\030\001 \003(\0132\023." +
      "popeye.proto.Point\022\023\n\013correlation\030\002 \001(\003\"" +
      "\177\n\nBatchReply\022\023\n\013correlation\030\001 \002(\003\022\017\n\007ba" +
      "tchId\030\002 \002(\003\022/\n\006status\030\003 \002(\0162\037.popeye.pro" +
      "to.BatchReply.Status\"\032\n\006Status\022\006\n\002OK\020\001\022\010",
      "\n\004FAIL\020\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_popeye_proto_Attribute_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_popeye_proto_Attribute_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_popeye_proto_Attribute_descriptor,
              new java.lang.String[] { "Name", "Value", },
              popeye.proto.Message.Attribute.class,
              popeye.proto.Message.Attribute.Builder.class);
          internal_static_popeye_proto_Point_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_popeye_proto_Point_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_popeye_proto_Point_descriptor,
              new java.lang.String[] { "Metric", "Timestamp", "Attributes", "IntValue", "FloatValue", },
              popeye.proto.Message.Point.class,
              popeye.proto.Message.Point.Builder.class);
          internal_static_popeye_proto_Batch_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_popeye_proto_Batch_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_popeye_proto_Batch_descriptor,
              new java.lang.String[] { "Point", "Correlation", },
              popeye.proto.Message.Batch.class,
              popeye.proto.Message.Batch.Builder.class);
          internal_static_popeye_proto_BatchReply_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_popeye_proto_BatchReply_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_popeye_proto_BatchReply_descriptor,
              new java.lang.String[] { "Correlation", "BatchId", "Status", },
              popeye.proto.Message.BatchReply.class,
              popeye.proto.Message.BatchReply.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
