#!/bin/bash
# postinst script for statbox-push-client-daemon
#
# see: dh_installdeb(1)

set -e

HOMEDIR=/home/statbox
grep -q '^statbox:' /etc/group || groupadd -g 10000 statbox
grep -q '^statbox:' /etc/passwd || useradd -s /bin/bash -m -g statbox -u 10000 -d $HOMEDIR statbox
mkdir -p /var/lib/statbox
mkdir -p /var/log/statbox
chown statbox:statbox /var/lib/statbox
chown statbox:statbox /var/log/statbox

env="unknown"

if [ -f /etc/yandex/environment.type ]
then
	env=`cat /etc/yandex/environment.type`
fi

for f in `ls -1 /etc/yandex/statbox-kafka/$env`
do
	cp /etc/yandex/statbox-kafka/$env/$f /etc/yandex/statbox-kafka/$f
done

# ln -sf /etc/nginx/sites-available/statbox-logbroker-$env.conf /etc/nginx/sites-enabled/statbox-logbroker.conf


#DEBHELPER#

exit 0

