// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/scala/qmon/transport/proto/message.proto

package qmon.transport.proto;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TagOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string name = 1;
    boolean hasName();
    String getName();
    
    // required string value = 2;
    boolean hasValue();
    String getValue();
  }
  public static final class Tag extends
      com.google.protobuf.GeneratedMessage
      implements TagOrBuilder {
    // Use Tag.newBuilder() to construct.
    private Tag(Builder builder) {
      super(builder);
    }
    private Tag(boolean noInit) {}
    
    private static final Tag defaultInstance;
    public static Tag getDefaultInstance() {
      return defaultInstance;
    }
    
    public Tag getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return qmon.transport.proto.Message.internal_static_qmon_transport_proto_Tag_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return qmon.transport.proto.Message.internal_static_qmon_transport_proto_Tag_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string value = 2;
    public static final int VALUE_FIELD_NUMBER = 2;
    private java.lang.Object value_;
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          value_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      name_ = "";
      value_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getValueBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getValueBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static qmon.transport.proto.Message.Tag parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static qmon.transport.proto.Message.Tag parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static qmon.transport.proto.Message.Tag parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static qmon.transport.proto.Message.Tag parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static qmon.transport.proto.Message.Tag parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static qmon.transport.proto.Message.Tag parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static qmon.transport.proto.Message.Tag parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static qmon.transport.proto.Message.Tag parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static qmon.transport.proto.Message.Tag parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static qmon.transport.proto.Message.Tag parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(qmon.transport.proto.Message.Tag prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements qmon.transport.proto.Message.TagOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return qmon.transport.proto.Message.internal_static_qmon_transport_proto_Tag_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return qmon.transport.proto.Message.internal_static_qmon_transport_proto_Tag_fieldAccessorTable;
      }
      
      // Construct using qmon.transport.proto.Message.Tag.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return qmon.transport.proto.Message.Tag.getDescriptor();
      }
      
      public qmon.transport.proto.Message.Tag getDefaultInstanceForType() {
        return qmon.transport.proto.Message.Tag.getDefaultInstance();
      }
      
      public qmon.transport.proto.Message.Tag build() {
        qmon.transport.proto.Message.Tag result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private qmon.transport.proto.Message.Tag buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        qmon.transport.proto.Message.Tag result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public qmon.transport.proto.Message.Tag buildPartial() {
        qmon.transport.proto.Message.Tag result = new qmon.transport.proto.Message.Tag(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof qmon.transport.proto.Message.Tag) {
          return mergeFrom((qmon.transport.proto.Message.Tag)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(qmon.transport.proto.Message.Tag other) {
        if (other == qmon.transport.proto.Message.Tag.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              value_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string name = 1;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
      }
      
      // required string value = 2;
      private java.lang.Object value_ = "";
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setValue(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      void setValue(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:qmon.transport.proto.Tag)
    }
    
    static {
      defaultInstance = new Tag(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:qmon.transport.proto.Tag)
  }
  
  public interface EventOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required bytes message = 1;
    boolean hasMessage();
    com.google.protobuf.ByteString getMessage();
    
    // repeated .qmon.transport.proto.Tag tags = 2;
    java.util.List<qmon.transport.proto.Message.Tag> 
        getTagsList();
    qmon.transport.proto.Message.Tag getTags(int index);
    int getTagsCount();
    java.util.List<? extends qmon.transport.proto.Message.TagOrBuilder> 
        getTagsOrBuilderList();
    qmon.transport.proto.Message.TagOrBuilder getTagsOrBuilder(
        int index);
  }
  public static final class Event extends
      com.google.protobuf.GeneratedMessage
      implements EventOrBuilder {
    // Use Event.newBuilder() to construct.
    private Event(Builder builder) {
      super(builder);
    }
    private Event(boolean noInit) {}
    
    private static final Event defaultInstance;
    public static Event getDefaultInstance() {
      return defaultInstance;
    }
    
    public Event getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return qmon.transport.proto.Message.internal_static_qmon_transport_proto_Event_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return qmon.transport.proto.Message.internal_static_qmon_transport_proto_Event_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required bytes message = 1;
    public static final int MESSAGE_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString message_;
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.google.protobuf.ByteString getMessage() {
      return message_;
    }
    
    // repeated .qmon.transport.proto.Tag tags = 2;
    public static final int TAGS_FIELD_NUMBER = 2;
    private java.util.List<qmon.transport.proto.Message.Tag> tags_;
    public java.util.List<qmon.transport.proto.Message.Tag> getTagsList() {
      return tags_;
    }
    public java.util.List<? extends qmon.transport.proto.Message.TagOrBuilder> 
        getTagsOrBuilderList() {
      return tags_;
    }
    public int getTagsCount() {
      return tags_.size();
    }
    public qmon.transport.proto.Message.Tag getTags(int index) {
      return tags_.get(index);
    }
    public qmon.transport.proto.Message.TagOrBuilder getTagsOrBuilder(
        int index) {
      return tags_.get(index);
    }
    
    private void initFields() {
      message_ = com.google.protobuf.ByteString.EMPTY;
      tags_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasMessage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getTagsCount(); i++) {
        if (!getTags(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, message_);
      }
      for (int i = 0; i < tags_.size(); i++) {
        output.writeMessage(2, tags_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, message_);
      }
      for (int i = 0; i < tags_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, tags_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static qmon.transport.proto.Message.Event parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static qmon.transport.proto.Message.Event parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static qmon.transport.proto.Message.Event parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static qmon.transport.proto.Message.Event parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static qmon.transport.proto.Message.Event parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static qmon.transport.proto.Message.Event parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static qmon.transport.proto.Message.Event parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static qmon.transport.proto.Message.Event parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static qmon.transport.proto.Message.Event parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static qmon.transport.proto.Message.Event parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(qmon.transport.proto.Message.Event prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements qmon.transport.proto.Message.EventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return qmon.transport.proto.Message.internal_static_qmon_transport_proto_Event_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return qmon.transport.proto.Message.internal_static_qmon_transport_proto_Event_fieldAccessorTable;
      }
      
      // Construct using qmon.transport.proto.Message.Event.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTagsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        message_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (tagsBuilder_ == null) {
          tags_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          tagsBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return qmon.transport.proto.Message.Event.getDescriptor();
      }
      
      public qmon.transport.proto.Message.Event getDefaultInstanceForType() {
        return qmon.transport.proto.Message.Event.getDefaultInstance();
      }
      
      public qmon.transport.proto.Message.Event build() {
        qmon.transport.proto.Message.Event result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private qmon.transport.proto.Message.Event buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        qmon.transport.proto.Message.Event result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public qmon.transport.proto.Message.Event buildPartial() {
        qmon.transport.proto.Message.Event result = new qmon.transport.proto.Message.Event(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.message_ = message_;
        if (tagsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            tags_ = java.util.Collections.unmodifiableList(tags_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.tags_ = tags_;
        } else {
          result.tags_ = tagsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof qmon.transport.proto.Message.Event) {
          return mergeFrom((qmon.transport.proto.Message.Event)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(qmon.transport.proto.Message.Event other) {
        if (other == qmon.transport.proto.Message.Event.getDefaultInstance()) return this;
        if (other.hasMessage()) {
          setMessage(other.getMessage());
        }
        if (tagsBuilder_ == null) {
          if (!other.tags_.isEmpty()) {
            if (tags_.isEmpty()) {
              tags_ = other.tags_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureTagsIsMutable();
              tags_.addAll(other.tags_);
            }
            onChanged();
          }
        } else {
          if (!other.tags_.isEmpty()) {
            if (tagsBuilder_.isEmpty()) {
              tagsBuilder_.dispose();
              tagsBuilder_ = null;
              tags_ = other.tags_;
              bitField0_ = (bitField0_ & ~0x00000002);
              tagsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getTagsFieldBuilder() : null;
            } else {
              tagsBuilder_.addAllMessages(other.tags_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasMessage()) {
          
          return false;
        }
        for (int i = 0; i < getTagsCount(); i++) {
          if (!getTags(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              message_ = input.readBytes();
              break;
            }
            case 18: {
              qmon.transport.proto.Message.Tag.Builder subBuilder = qmon.transport.proto.Message.Tag.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addTags(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required bytes message = 1;
      private com.google.protobuf.ByteString message_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.google.protobuf.ByteString getMessage() {
        return message_;
      }
      public Builder setMessage(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        message_ = value;
        onChanged();
        return this;
      }
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000001);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      
      // repeated .qmon.transport.proto.Tag tags = 2;
      private java.util.List<qmon.transport.proto.Message.Tag> tags_ =
        java.util.Collections.emptyList();
      private void ensureTagsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          tags_ = new java.util.ArrayList<qmon.transport.proto.Message.Tag>(tags_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          qmon.transport.proto.Message.Tag, qmon.transport.proto.Message.Tag.Builder, qmon.transport.proto.Message.TagOrBuilder> tagsBuilder_;
      
      public java.util.List<qmon.transport.proto.Message.Tag> getTagsList() {
        if (tagsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(tags_);
        } else {
          return tagsBuilder_.getMessageList();
        }
      }
      public int getTagsCount() {
        if (tagsBuilder_ == null) {
          return tags_.size();
        } else {
          return tagsBuilder_.getCount();
        }
      }
      public qmon.transport.proto.Message.Tag getTags(int index) {
        if (tagsBuilder_ == null) {
          return tags_.get(index);
        } else {
          return tagsBuilder_.getMessage(index);
        }
      }
      public Builder setTags(
          int index, qmon.transport.proto.Message.Tag value) {
        if (tagsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTagsIsMutable();
          tags_.set(index, value);
          onChanged();
        } else {
          tagsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setTags(
          int index, qmon.transport.proto.Message.Tag.Builder builderForValue) {
        if (tagsBuilder_ == null) {
          ensureTagsIsMutable();
          tags_.set(index, builderForValue.build());
          onChanged();
        } else {
          tagsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addTags(qmon.transport.proto.Message.Tag value) {
        if (tagsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTagsIsMutable();
          tags_.add(value);
          onChanged();
        } else {
          tagsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addTags(
          int index, qmon.transport.proto.Message.Tag value) {
        if (tagsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTagsIsMutable();
          tags_.add(index, value);
          onChanged();
        } else {
          tagsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addTags(
          qmon.transport.proto.Message.Tag.Builder builderForValue) {
        if (tagsBuilder_ == null) {
          ensureTagsIsMutable();
          tags_.add(builderForValue.build());
          onChanged();
        } else {
          tagsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addTags(
          int index, qmon.transport.proto.Message.Tag.Builder builderForValue) {
        if (tagsBuilder_ == null) {
          ensureTagsIsMutable();
          tags_.add(index, builderForValue.build());
          onChanged();
        } else {
          tagsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllTags(
          java.lang.Iterable<? extends qmon.transport.proto.Message.Tag> values) {
        if (tagsBuilder_ == null) {
          ensureTagsIsMutable();
          super.addAll(values, tags_);
          onChanged();
        } else {
          tagsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearTags() {
        if (tagsBuilder_ == null) {
          tags_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          tagsBuilder_.clear();
        }
        return this;
      }
      public Builder removeTags(int index) {
        if (tagsBuilder_ == null) {
          ensureTagsIsMutable();
          tags_.remove(index);
          onChanged();
        } else {
          tagsBuilder_.remove(index);
        }
        return this;
      }
      public qmon.transport.proto.Message.Tag.Builder getTagsBuilder(
          int index) {
        return getTagsFieldBuilder().getBuilder(index);
      }
      public qmon.transport.proto.Message.TagOrBuilder getTagsOrBuilder(
          int index) {
        if (tagsBuilder_ == null) {
          return tags_.get(index);  } else {
          return tagsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends qmon.transport.proto.Message.TagOrBuilder> 
           getTagsOrBuilderList() {
        if (tagsBuilder_ != null) {
          return tagsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(tags_);
        }
      }
      public qmon.transport.proto.Message.Tag.Builder addTagsBuilder() {
        return getTagsFieldBuilder().addBuilder(
            qmon.transport.proto.Message.Tag.getDefaultInstance());
      }
      public qmon.transport.proto.Message.Tag.Builder addTagsBuilder(
          int index) {
        return getTagsFieldBuilder().addBuilder(
            index, qmon.transport.proto.Message.Tag.getDefaultInstance());
      }
      public java.util.List<qmon.transport.proto.Message.Tag.Builder> 
           getTagsBuilderList() {
        return getTagsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          qmon.transport.proto.Message.Tag, qmon.transport.proto.Message.Tag.Builder, qmon.transport.proto.Message.TagOrBuilder> 
          getTagsFieldBuilder() {
        if (tagsBuilder_ == null) {
          tagsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              qmon.transport.proto.Message.Tag, qmon.transport.proto.Message.Tag.Builder, qmon.transport.proto.Message.TagOrBuilder>(
                  tags_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          tags_ = null;
        }
        return tagsBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:qmon.transport.proto.Event)
    }
    
    static {
      defaultInstance = new Event(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:qmon.transport.proto.Event)
  }
  
  public interface BatchOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int64 correlation = 1;
    boolean hasCorrelation();
    long getCorrelation();
    
    // repeated .qmon.transport.proto.Event event = 2;
    java.util.List<qmon.transport.proto.Message.Event> 
        getEventList();
    qmon.transport.proto.Message.Event getEvent(int index);
    int getEventCount();
    java.util.List<? extends qmon.transport.proto.Message.EventOrBuilder> 
        getEventOrBuilderList();
    qmon.transport.proto.Message.EventOrBuilder getEventOrBuilder(
        int index);
  }
  public static final class Batch extends
      com.google.protobuf.GeneratedMessage
      implements BatchOrBuilder {
    // Use Batch.newBuilder() to construct.
    private Batch(Builder builder) {
      super(builder);
    }
    private Batch(boolean noInit) {}
    
    private static final Batch defaultInstance;
    public static Batch getDefaultInstance() {
      return defaultInstance;
    }
    
    public Batch getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return qmon.transport.proto.Message.internal_static_qmon_transport_proto_Batch_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return qmon.transport.proto.Message.internal_static_qmon_transport_proto_Batch_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional int64 correlation = 1;
    public static final int CORRELATION_FIELD_NUMBER = 1;
    private long correlation_;
    public boolean hasCorrelation() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getCorrelation() {
      return correlation_;
    }
    
    // repeated .qmon.transport.proto.Event event = 2;
    public static final int EVENT_FIELD_NUMBER = 2;
    private java.util.List<qmon.transport.proto.Message.Event> event_;
    public java.util.List<qmon.transport.proto.Message.Event> getEventList() {
      return event_;
    }
    public java.util.List<? extends qmon.transport.proto.Message.EventOrBuilder> 
        getEventOrBuilderList() {
      return event_;
    }
    public int getEventCount() {
      return event_.size();
    }
    public qmon.transport.proto.Message.Event getEvent(int index) {
      return event_.get(index);
    }
    public qmon.transport.proto.Message.EventOrBuilder getEventOrBuilder(
        int index) {
      return event_.get(index);
    }
    
    private void initFields() {
      correlation_ = 0L;
      event_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getEventCount(); i++) {
        if (!getEvent(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, correlation_);
      }
      for (int i = 0; i < event_.size(); i++) {
        output.writeMessage(2, event_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, correlation_);
      }
      for (int i = 0; i < event_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, event_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static qmon.transport.proto.Message.Batch parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static qmon.transport.proto.Message.Batch parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static qmon.transport.proto.Message.Batch parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static qmon.transport.proto.Message.Batch parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static qmon.transport.proto.Message.Batch parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static qmon.transport.proto.Message.Batch parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static qmon.transport.proto.Message.Batch parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static qmon.transport.proto.Message.Batch parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static qmon.transport.proto.Message.Batch parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static qmon.transport.proto.Message.Batch parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(qmon.transport.proto.Message.Batch prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements qmon.transport.proto.Message.BatchOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return qmon.transport.proto.Message.internal_static_qmon_transport_proto_Batch_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return qmon.transport.proto.Message.internal_static_qmon_transport_proto_Batch_fieldAccessorTable;
      }
      
      // Construct using qmon.transport.proto.Message.Batch.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getEventFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        correlation_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (eventBuilder_ == null) {
          event_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          eventBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return qmon.transport.proto.Message.Batch.getDescriptor();
      }
      
      public qmon.transport.proto.Message.Batch getDefaultInstanceForType() {
        return qmon.transport.proto.Message.Batch.getDefaultInstance();
      }
      
      public qmon.transport.proto.Message.Batch build() {
        qmon.transport.proto.Message.Batch result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private qmon.transport.proto.Message.Batch buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        qmon.transport.proto.Message.Batch result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public qmon.transport.proto.Message.Batch buildPartial() {
        qmon.transport.proto.Message.Batch result = new qmon.transport.proto.Message.Batch(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.correlation_ = correlation_;
        if (eventBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            event_ = java.util.Collections.unmodifiableList(event_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.event_ = event_;
        } else {
          result.event_ = eventBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof qmon.transport.proto.Message.Batch) {
          return mergeFrom((qmon.transport.proto.Message.Batch)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(qmon.transport.proto.Message.Batch other) {
        if (other == qmon.transport.proto.Message.Batch.getDefaultInstance()) return this;
        if (other.hasCorrelation()) {
          setCorrelation(other.getCorrelation());
        }
        if (eventBuilder_ == null) {
          if (!other.event_.isEmpty()) {
            if (event_.isEmpty()) {
              event_ = other.event_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureEventIsMutable();
              event_.addAll(other.event_);
            }
            onChanged();
          }
        } else {
          if (!other.event_.isEmpty()) {
            if (eventBuilder_.isEmpty()) {
              eventBuilder_.dispose();
              eventBuilder_ = null;
              event_ = other.event_;
              bitField0_ = (bitField0_ & ~0x00000002);
              eventBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getEventFieldBuilder() : null;
            } else {
              eventBuilder_.addAllMessages(other.event_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getEventCount(); i++) {
          if (!getEvent(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              correlation_ = input.readInt64();
              break;
            }
            case 18: {
              qmon.transport.proto.Message.Event.Builder subBuilder = qmon.transport.proto.Message.Event.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addEvent(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int64 correlation = 1;
      private long correlation_ ;
      public boolean hasCorrelation() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getCorrelation() {
        return correlation_;
      }
      public Builder setCorrelation(long value) {
        bitField0_ |= 0x00000001;
        correlation_ = value;
        onChanged();
        return this;
      }
      public Builder clearCorrelation() {
        bitField0_ = (bitField0_ & ~0x00000001);
        correlation_ = 0L;
        onChanged();
        return this;
      }
      
      // repeated .qmon.transport.proto.Event event = 2;
      private java.util.List<qmon.transport.proto.Message.Event> event_ =
        java.util.Collections.emptyList();
      private void ensureEventIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          event_ = new java.util.ArrayList<qmon.transport.proto.Message.Event>(event_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          qmon.transport.proto.Message.Event, qmon.transport.proto.Message.Event.Builder, qmon.transport.proto.Message.EventOrBuilder> eventBuilder_;
      
      public java.util.List<qmon.transport.proto.Message.Event> getEventList() {
        if (eventBuilder_ == null) {
          return java.util.Collections.unmodifiableList(event_);
        } else {
          return eventBuilder_.getMessageList();
        }
      }
      public int getEventCount() {
        if (eventBuilder_ == null) {
          return event_.size();
        } else {
          return eventBuilder_.getCount();
        }
      }
      public qmon.transport.proto.Message.Event getEvent(int index) {
        if (eventBuilder_ == null) {
          return event_.get(index);
        } else {
          return eventBuilder_.getMessage(index);
        }
      }
      public Builder setEvent(
          int index, qmon.transport.proto.Message.Event value) {
        if (eventBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEventIsMutable();
          event_.set(index, value);
          onChanged();
        } else {
          eventBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setEvent(
          int index, qmon.transport.proto.Message.Event.Builder builderForValue) {
        if (eventBuilder_ == null) {
          ensureEventIsMutable();
          event_.set(index, builderForValue.build());
          onChanged();
        } else {
          eventBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addEvent(qmon.transport.proto.Message.Event value) {
        if (eventBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEventIsMutable();
          event_.add(value);
          onChanged();
        } else {
          eventBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addEvent(
          int index, qmon.transport.proto.Message.Event value) {
        if (eventBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEventIsMutable();
          event_.add(index, value);
          onChanged();
        } else {
          eventBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addEvent(
          qmon.transport.proto.Message.Event.Builder builderForValue) {
        if (eventBuilder_ == null) {
          ensureEventIsMutable();
          event_.add(builderForValue.build());
          onChanged();
        } else {
          eventBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addEvent(
          int index, qmon.transport.proto.Message.Event.Builder builderForValue) {
        if (eventBuilder_ == null) {
          ensureEventIsMutable();
          event_.add(index, builderForValue.build());
          onChanged();
        } else {
          eventBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllEvent(
          java.lang.Iterable<? extends qmon.transport.proto.Message.Event> values) {
        if (eventBuilder_ == null) {
          ensureEventIsMutable();
          super.addAll(values, event_);
          onChanged();
        } else {
          eventBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearEvent() {
        if (eventBuilder_ == null) {
          event_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          eventBuilder_.clear();
        }
        return this;
      }
      public Builder removeEvent(int index) {
        if (eventBuilder_ == null) {
          ensureEventIsMutable();
          event_.remove(index);
          onChanged();
        } else {
          eventBuilder_.remove(index);
        }
        return this;
      }
      public qmon.transport.proto.Message.Event.Builder getEventBuilder(
          int index) {
        return getEventFieldBuilder().getBuilder(index);
      }
      public qmon.transport.proto.Message.EventOrBuilder getEventOrBuilder(
          int index) {
        if (eventBuilder_ == null) {
          return event_.get(index);  } else {
          return eventBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends qmon.transport.proto.Message.EventOrBuilder> 
           getEventOrBuilderList() {
        if (eventBuilder_ != null) {
          return eventBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(event_);
        }
      }
      public qmon.transport.proto.Message.Event.Builder addEventBuilder() {
        return getEventFieldBuilder().addBuilder(
            qmon.transport.proto.Message.Event.getDefaultInstance());
      }
      public qmon.transport.proto.Message.Event.Builder addEventBuilder(
          int index) {
        return getEventFieldBuilder().addBuilder(
            index, qmon.transport.proto.Message.Event.getDefaultInstance());
      }
      public java.util.List<qmon.transport.proto.Message.Event.Builder> 
           getEventBuilderList() {
        return getEventFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          qmon.transport.proto.Message.Event, qmon.transport.proto.Message.Event.Builder, qmon.transport.proto.Message.EventOrBuilder> 
          getEventFieldBuilder() {
        if (eventBuilder_ == null) {
          eventBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              qmon.transport.proto.Message.Event, qmon.transport.proto.Message.Event.Builder, qmon.transport.proto.Message.EventOrBuilder>(
                  event_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          event_ = null;
        }
        return eventBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:qmon.transport.proto.Batch)
    }
    
    static {
      defaultInstance = new Batch(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:qmon.transport.proto.Batch)
  }
  
  public interface BatchReplyOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int64 correlation = 1;
    boolean hasCorrelation();
    long getCorrelation();
    
    // required .qmon.transport.proto.BatchReply.Status status = 2;
    boolean hasStatus();
    qmon.transport.proto.Message.BatchReply.Status getStatus();
  }
  public static final class BatchReply extends
      com.google.protobuf.GeneratedMessage
      implements BatchReplyOrBuilder {
    // Use BatchReply.newBuilder() to construct.
    private BatchReply(Builder builder) {
      super(builder);
    }
    private BatchReply(boolean noInit) {}
    
    private static final BatchReply defaultInstance;
    public static BatchReply getDefaultInstance() {
      return defaultInstance;
    }
    
    public BatchReply getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return qmon.transport.proto.Message.internal_static_qmon_transport_proto_BatchReply_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return qmon.transport.proto.Message.internal_static_qmon_transport_proto_BatchReply_fieldAccessorTable;
    }
    
    public enum Status
        implements com.google.protobuf.ProtocolMessageEnum {
      OK(0, 1),
      FAIL(1, 2),
      ;
      
      public static final int OK_VALUE = 1;
      public static final int FAIL_VALUE = 2;
      
      
      public final int getNumber() { return value; }
      
      public static Status valueOf(int value) {
        switch (value) {
          case 1: return OK;
          case 2: return FAIL;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Status>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Status>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Status>() {
              public Status findValueByNumber(int number) {
                return Status.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return qmon.transport.proto.Message.BatchReply.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Status[] VALUES = {
        OK, FAIL, 
      };
      
      public static Status valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Status(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:qmon.transport.proto.BatchReply.Status)
    }
    
    private int bitField0_;
    // optional int64 correlation = 1;
    public static final int CORRELATION_FIELD_NUMBER = 1;
    private long correlation_;
    public boolean hasCorrelation() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getCorrelation() {
      return correlation_;
    }
    
    // required .qmon.transport.proto.BatchReply.Status status = 2;
    public static final int STATUS_FIELD_NUMBER = 2;
    private qmon.transport.proto.Message.BatchReply.Status status_;
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public qmon.transport.proto.Message.BatchReply.Status getStatus() {
      return status_;
    }
    
    private void initFields() {
      correlation_ = 0L;
      status_ = qmon.transport.proto.Message.BatchReply.Status.OK;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, correlation_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, status_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, correlation_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, status_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static qmon.transport.proto.Message.BatchReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static qmon.transport.proto.Message.BatchReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static qmon.transport.proto.Message.BatchReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static qmon.transport.proto.Message.BatchReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static qmon.transport.proto.Message.BatchReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static qmon.transport.proto.Message.BatchReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static qmon.transport.proto.Message.BatchReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static qmon.transport.proto.Message.BatchReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static qmon.transport.proto.Message.BatchReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static qmon.transport.proto.Message.BatchReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(qmon.transport.proto.Message.BatchReply prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements qmon.transport.proto.Message.BatchReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return qmon.transport.proto.Message.internal_static_qmon_transport_proto_BatchReply_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return qmon.transport.proto.Message.internal_static_qmon_transport_proto_BatchReply_fieldAccessorTable;
      }
      
      // Construct using qmon.transport.proto.Message.BatchReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        correlation_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = qmon.transport.proto.Message.BatchReply.Status.OK;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return qmon.transport.proto.Message.BatchReply.getDescriptor();
      }
      
      public qmon.transport.proto.Message.BatchReply getDefaultInstanceForType() {
        return qmon.transport.proto.Message.BatchReply.getDefaultInstance();
      }
      
      public qmon.transport.proto.Message.BatchReply build() {
        qmon.transport.proto.Message.BatchReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private qmon.transport.proto.Message.BatchReply buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        qmon.transport.proto.Message.BatchReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public qmon.transport.proto.Message.BatchReply buildPartial() {
        qmon.transport.proto.Message.BatchReply result = new qmon.transport.proto.Message.BatchReply(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.correlation_ = correlation_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.status_ = status_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof qmon.transport.proto.Message.BatchReply) {
          return mergeFrom((qmon.transport.proto.Message.BatchReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(qmon.transport.proto.Message.BatchReply other) {
        if (other == qmon.transport.proto.Message.BatchReply.getDefaultInstance()) return this;
        if (other.hasCorrelation()) {
          setCorrelation(other.getCorrelation());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasStatus()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              correlation_ = input.readInt64();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              qmon.transport.proto.Message.BatchReply.Status value = qmon.transport.proto.Message.BatchReply.Status.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                status_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int64 correlation = 1;
      private long correlation_ ;
      public boolean hasCorrelation() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getCorrelation() {
        return correlation_;
      }
      public Builder setCorrelation(long value) {
        bitField0_ |= 0x00000001;
        correlation_ = value;
        onChanged();
        return this;
      }
      public Builder clearCorrelation() {
        bitField0_ = (bitField0_ & ~0x00000001);
        correlation_ = 0L;
        onChanged();
        return this;
      }
      
      // required .qmon.transport.proto.BatchReply.Status status = 2;
      private qmon.transport.proto.Message.BatchReply.Status status_ = qmon.transport.proto.Message.BatchReply.Status.OK;
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public qmon.transport.proto.Message.BatchReply.Status getStatus() {
        return status_;
      }
      public Builder setStatus(qmon.transport.proto.Message.BatchReply.Status value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        status_ = value;
        onChanged();
        return this;
      }
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = qmon.transport.proto.Message.BatchReply.Status.OK;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:qmon.transport.proto.BatchReply)
    }
    
    static {
      defaultInstance = new BatchReply(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:qmon.transport.proto.BatchReply)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_qmon_transport_proto_Tag_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_qmon_transport_proto_Tag_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_qmon_transport_proto_Event_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_qmon_transport_proto_Event_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_qmon_transport_proto_Batch_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_qmon_transport_proto_Batch_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_qmon_transport_proto_BatchReply_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_qmon_transport_proto_BatchReply_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n1src/main/scala/qmon/transport/proto/me" +
      "ssage.proto\022\024qmon.transport.proto\"\"\n\003Tag" +
      "\022\014\n\004name\030\001 \002(\t\022\r\n\005value\030\002 \002(\t\"A\n\005Event\022\017" +
      "\n\007message\030\001 \002(\014\022\'\n\004tags\030\002 \003(\0132\031.qmon.tra" +
      "nsport.proto.Tag\"H\n\005Batch\022\023\n\013correlation" +
      "\030\001 \001(\003\022*\n\005event\030\002 \003(\0132\033.qmon.transport.p" +
      "roto.Event\"v\n\nBatchReply\022\023\n\013correlation\030" +
      "\001 \001(\003\0227\n\006status\030\002 \002(\0162\'.qmon.transport.p" +
      "roto.BatchReply.Status\"\032\n\006Status\022\006\n\002OK\020\001" +
      "\022\010\n\004FAIL\020\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_qmon_transport_proto_Tag_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_qmon_transport_proto_Tag_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_qmon_transport_proto_Tag_descriptor,
              new java.lang.String[] { "Name", "Value", },
              qmon.transport.proto.Message.Tag.class,
              qmon.transport.proto.Message.Tag.Builder.class);
          internal_static_qmon_transport_proto_Event_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_qmon_transport_proto_Event_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_qmon_transport_proto_Event_descriptor,
              new java.lang.String[] { "Message", "Tags", },
              qmon.transport.proto.Message.Event.class,
              qmon.transport.proto.Message.Event.Builder.class);
          internal_static_qmon_transport_proto_Batch_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_qmon_transport_proto_Batch_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_qmon_transport_proto_Batch_descriptor,
              new java.lang.String[] { "Correlation", "Event", },
              qmon.transport.proto.Message.Batch.class,
              qmon.transport.proto.Message.Batch.Builder.class);
          internal_static_qmon_transport_proto_BatchReply_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_qmon_transport_proto_BatchReply_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_qmon_transport_proto_BatchReply_descriptor,
              new java.lang.String[] { "Correlation", "Status", },
              qmon.transport.proto.Message.BatchReply.class,
              qmon.transport.proto.Message.BatchReply.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
